version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongo-data:/data/db
    networks:
      - waiter-network
    restart: unless-stopped

  api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    ports:
      - 3333:3333
    volumes:
      - .:/usr/src/app/apps/api
      - /usr/src/app/apps/api/node_modules
    depends_on:
      - mongo
    networks:
      - waiter-network
    restart: unless-stopped
    env_file:
    - .env

networks:
  waiter-network:
    driver: bridge
